# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Unimd2pdf < Formula
  desc "Universal Markdown to PDF converter"
  homepage "https://github.com/bianbbc87/unimd2pdf"
  version "0.1.0"
  license "MIT"

  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/bianbbc87/unimd2pdf/releases/download/v0.1.0/unimd2pdf_0.1.0_darwin_amd64.tar.gz"
      sha256 "b1f0d1c546e55ae893c0163def7a68203dff8b52af406b18ca36f335858e16c8"

      define_method(:install) do
        bin.install "unimd2pdf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/bianbbc87/unimd2pdf/releases/download/v0.1.0/unimd2pdf_0.1.0_darwin_arm64.tar.gz"
      sha256 "54db9ed4f79c6503611b810e869a344300a69c91e4bdda007d79c6922154221b"

      define_method(:install) do
        bin.install "unimd2pdf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/bianbbc87/unimd2pdf/releases/download/v0.1.0/unimd2pdf_0.1.0_linux_amd64.tar.gz"
      sha256 "93f81e877a4f585020611305959b9180c8c193308d024dd643b258cbda5332b5"
      define_method(:install) do
        bin.install "unimd2pdf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bianbbc87/unimd2pdf/releases/download/v0.1.0/unimd2pdf_0.1.0_linux_arm64.tar.gz"
      sha256 "3eb9c6f0488f52a3109102c82132e7b144da6b07cb4f8d208bffd1a0e151bd23"
      define_method(:install) do
        bin.install "unimd2pdf"
      end
    end
  end

  test do
    system "#{bin}/unimd2pdf", "--version"
  end
end
