# This file was generated by GoReleaser. DO NOT EDIT.
cask "unimd2pdf" do
  version "0.1.4"

  on_macos do
    on_intel do
      sha256 "66512c49d50ef60d19a18304a844a44cb9bc2c712558293c7e12c33902643016"
      url "https://github.com/bianbbc87/unimd2pdf/releases/download/v#{version}/unimd2pdf_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6fbdbe29709a8857cb0a626dffcf1309bf232bc278aeca2f8945f26d3b0bbfff"
      url "https://github.com/bianbbc87/unimd2pdf/releases/download/v#{version}/unimd2pdf_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "00c84c6bd43ea49360bc1ab2839d8d320996604031b3515d4fe71fff5129c363"
      url "https://github.com/bianbbc87/unimd2pdf/releases/download/v#{version}/unimd2pdf_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5de5033c580a851817041ef80af74e6e49deafa8330cac46ddcbb0796b9dbe09"
      url "https://github.com/bianbbc87/unimd2pdf/releases/download/v#{version}/unimd2pdf_#{version}_linux_arm64.tar.gz"
    end
  end

  name "unimd2pdf"
  desc "Universal Markdown to PDF converter"
  homepage "https://github.com/bianbbc87/unimd2pdf"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "unimd2pdf"

  postflight do
    if OS.mac? && Hardware::CPU.arm?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/unimd2pdf"]
    end
  end

  # No zap stanza required

end
